#!/bin/bash
if [ ! -f Release/DigitalSignage ]; then
  echo "Please ensure you have built a \"Release\" build!"
  exit 1
else
  pathout="DigitalSignage-DPKG/"
  majorv="0.2.$(date +%s)"
  # oneiric
  newversion="${majorv}.1-oneiric"
  echo Cleaning Old Files...
  rm -rf ${pathout}opt
  echo Updating Version to $newversion
  echo $newversion > res/defaults/vstr
  echo "Populating Package Container from compiled source (RELEASE)..."
  mkdir -p ${pathout}opt/digitalsignage/deps
  cp -aR Release/DigitalSignage ${pathout}opt/digitalsignage/
  cp -aR res/* ${pathout}opt/digitalsignage/
  cp -aR ../get_iplayer ${pathout}opt/digitalsignage/deps/ip/
  rm -rf ${pathout}opt/digitalsignage/deps/ip/.git
  echo Files Copied
  echo Building .deb
  echo "Package: digitalsignage" > ${pathout}DEBIAN/control
  echo "Version: $newversion" >> ${pathout}DEBIAN/control
  echo "Section: base" >> ${pathout}DEBIAN/control
  echo "Priority: optional" >> ${pathout}DEBIAN/control
  echo "Installed-Size: 5128" >> ${pathout}DEBIAN/control
  echo "Architecture: amd64" >> ${pathout}DEBIAN/control
  echo "Depends: libsdl1.2debian, libsdl-image1.2, libsdl-ttf2.0-0, mplayer, rtmpdump, cutycapt, libwww-perl, apache2, libapache2-mod-php5, libicu48" >> ${pathout}/DEBIAN/control
  echo "Maintainer: paulw@hardmilk.com" >> ${pathout}DEBIAN/control
  echo "Description: Digital Signage System for Ubuntu-based Linux Distributions." >> ${pathout}DEBIAN/control
  dpkg --build DigitalSignage-DPKG ./
  mkdir -p DPKG-Out/oneiric
  echo Moving to DPKG-Out...
  mv digitalsignage_${newversion}_amd64.deb DPKG-Out/oneiric/

  # precise
  newversion="${majorv}.2-precise"
  echo Cleaning Old Files...
  rm -rf ${pathout}opt
  echo Updating Version to $newversion
  echo $newversion > res/defaults/vstr
  echo "Populating Package Container from compiled source (RELEASE)..."
  mkdir -p ${pathout}opt/digitalsignage/deps
  cp -aR Release/DigitalSignage ${pathout}opt/digitalsignage/
  cp -aR res/* ${pathout}opt/digitalsignage/
  cp -aR ../get_iplayer ${pathout}opt/digitalsignage/deps/ip/
  rm -rf ${pathout}opt/digitalsignage/deps/ip/.git
  echo Files Copied
  echo Building .deb
  echo "Package: digitalsignage" > ${pathout}DEBIAN/control
  echo "Version: $newversion" >> ${pathout}DEBIAN/control
  echo "Section: base" >> ${pathout}DEBIAN/control
  echo "Priority: optional" >> ${pathout}DEBIAN/control
  echo "Installed-Size: 5128" >> ${pathout}DEBIAN/control
  echo "Architecture: amd64" >> ${pathout}DEBIAN/control
  echo "Depends: libsdl1.2debian, libsdl-image1.2, libsdl-ttf2.0-0, mplayer, rtmpdump, cutycapt, libwww-perl, apache2, libapache2-mod-php5, libicu48" >> ${pathout}/DEBIAN/control
  echo "Maintainer: paulw@hardmilk.com" >> ${pathout}DEBIAN/control
  echo "Description: Digital Signage System for Ubuntu-based Linux Distributions." >> ${pathout}DEBIAN/control
  dpkg --build DigitalSignage-DPKG ./
  mkdir -p DPKG-Out/precise
  echo Moving to DPKG-Out...
  mv digitalsignage_${newversion}_amd64.deb DPKG-Out/precise/

  # quantal
  newversion="${majorv}.3-quantal"
  echo Cleaning Old Files...
  rm -rf ${pathout}opt
  echo Updating Version to $newversion
  echo $newversion > res/defaults/vstr
  echo "Populating Package Container from compiled source (RELEASE)..."
  mkdir -p ${pathout}opt/digitalsignage/deps
  cp -aR Release/DigitalSignage ${pathout}opt/digitalsignage/
  cp -aR res/* ${pathout}opt/digitalsignage/
  cp -aR ../get_iplayer ${pathout}opt/digitalsignage/deps/ip/
  rm -rf ${pathout}opt/digitalsignage/deps/ip/.git
  echo Files Copied
  echo Building .deb
  echo "Package: digitalsignage" > ${pathout}DEBIAN/control
  echo "Version: $newversion" >> ${pathout}DEBIAN/control
  echo "Section: base" >> ${pathout}DEBIAN/control
  echo "Priority: optional" >> ${pathout}DEBIAN/control
  echo "Installed-Size: 5128" >> ${pathout}DEBIAN/control
  echo "Architecture: amd64" >> ${pathout}DEBIAN/control
  echo "Depends: libsdl1.2debian, libsdl-image1.2, libsdl-ttf2.0-0, mplayer, rtmpdump, cutycapt, libwww-perl, apache2, libapache2-mod-php5, libicu48" >> ${pathout}/DEBIAN/control
  echo "Maintainer: paulw@hardmilk.com" >> ${pathout}DEBIAN/control
  echo "Description: Digital Signage System for Ubuntu-based Linux Distributions." >> ${pathout}DEBIAN/control
  dpkg --build DigitalSignage-DPKG ./
  mkdir -p DPKG-Out/quantal
  echo Moving to DPKG-Out...
  mv digitalsignage_${newversion}_amd64.deb DPKG-Out/quantal/
  echo Done!
fi
